# R2D2 setting
hidden_state_dim: 512
sequence_length: 30

batch_size: 256
lr: 0.0000625
agc_clipping: 0.02
gamma: 0.99
dropout_p: 0.1
eval_frequency: 200
actor_update_frequency: 1000
learner_start_update_memory_size: 1000
model_name: R2D2_4_11_1
resume: ''

memory_size_bound: 10000
priority_alpha: 0.6
priority_beta: 0.5
nstep: 4
update_lambda: 1.0

target_net_update_frequency: 2500
actor_total_num: 24
actor_epsilon: 0.4
actor_alpha: 7
